#!/bin/sh

set -eu

# chroot $1 apt install -y cage chromium

# APP="/usr/bin/chromium-browser http://127.0.0.1:3610/ \
# --kiosk --noerrdialogs --disable-translate \
# --disable-infobars --no-first-run --disable-first-run-ui --disable-pinch --overscroll-history-navigation=disabled \
# --disable-features=TouchpadOverscrollHistoryNavigation --disable-restore-session-state --ozone-platform=wayland \
# --allow-insecure-localhost --app-auto-launched --disable-extensions --disable-logging --disable-pull-to-refresh-effect --no-default-browser-check --disable-plugins \
# --disable-default-apps --disable-background-timer-throttling --disable-background-networking --disable-notifications --disable-single-click-autofill \
# --enable-features=OverlayScrollbar --start-maximized --no-sandbox --disable-crash-reporter --no-crashpad"

# cat ../services/kiosk.service.tpl | sed \
#    -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
#    -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
#    -e "s|<KIOSK_APP>|$APP|g" \
#    > $1/etc/systemd/system/kiosk.service

cat ../services/kiosk.service.tpl > $1/etc/systemd/system/kiosk.service
$BDEBSTRAP_HOOKS/enable-units "$1" kiosk

cat ../services/ballot-back.service.tpl > $1/etc/systemd/system/ballot-back.service
$BDEBSTRAP_HOOKS/enable-units "$1" ballot-back

# mkdir -p "$1/etc/xdg/weston"
# cat ../services/weston.ini.tpl > "$1/etc/xdg/weston/weston.ini"
mkdir -p "$1/etc/xdg/cog"
cat ../services/cog.ini.tpl > "$1/etc/xdg/cog/cog.ini"

mkdir -p "$1/data/app"

# mkdir -p "$1/etc/udev/rules.d"
# cat ../services/72-seat.rules.tpl > "$1/etc/udev/rules.d/72-rp1_drm-seat.rules"

# cat ../services/plymouthd.conf > $1/etc/plymouth/plymouthd.conf
# chmod a+rx "$1/etc/plymouth/plymouthd.conf"
# chmod a+rx "$1/etc/xdg/weston/weston.ini"

# cat ../services/quit-splash.service.tpl > $1/lib/systemd/system/plymouth-quit.service

# cat ../services/quit-splash.service.tpl > $1/lib/systemd/system/quit-splash.service
# $BDEBSTRAP_HOOKS/enable-units "$1" quit-splash

# cat ../services/eeprom-tool.service.tpl > $1/etc/systemd/system/eeprom-tool.service
# $BDEBSTRAP_HOOKS/enable-units "$1" eeprom-tool

