#!/bin/sh

set -eu

cat ../services/cog.service.tpl > $1/etc/systemd/system/cog.service
# chmod 777 "$1/etc/systemd/system/cog.service"
$BDEBSTRAP_HOOKS/enable-units "$1" cog

cat ../services/ballot-back.service.tpl > $1/etc/systemd/system/ballot-back.service
# chmod 777 "$1/etc/systemd/system/ballot-back.service"
$BDEBSTRAP_HOOKS/enable-units "$1" ballot-back

mkdir -p "$1/etc/xdg/cog"
cat ../services/cog.ini.tpl > "$1/etc/xdg/cog/cog.ini"

# mkdir -p "$1/etc/udev/rules.d"
# cat ../services/72-seat.rules.tpl > "$1/etc/udev/rules.d/72-rp1_drm-seat.rules"

# cat ../services/eeprom-tool.service.tpl > $1/etc/systemd/system/eeprom-tool.service
# $BDEBSTRAP_HOOKS/enable-units "$1" eeprom-tool

