#!/bin/sh

# chroot $1 apt install -y cage chromium

APP="/usr/bin/chromium-browser http://127.0.0.1:3610/ \
--kiosk --noerrdialogs --disable-translate \
--disable-infobars --no-first-run --disable-first-run-ui --disable-pinch --overscroll-history-navigation=disabled \
--disable-features=TouchpadOverscrollHistoryNavigation --disable-restore-session-state --ozone-platform=wayland \
--allow-insecure-localhost --app-auto-launched --disable-extensions --disable-logging --disable-pull-to-refresh-effect --no-default-browser-check --disable-plugins \
--disable-default-apps --disable-background-timer-throttling --disable-background-networking --disable-notifications --disable-single-click-autofill \
--enable-features=OverlayScrollbar --start-maximized --no-sandbox --disable-crash-reporter --no-crashpad"

cat ../services/kiosk.service.tpl | sed \
   -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
   -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
   -e "s|<KIOSK_APP>|$APP|g" \
   > $1/etc/systemd/system/kiosk.service

$BDEBSTRAP_HOOKS/enable-units "$1" kiosk

cat ../services/ballot-front.service.tpl > $1/etc/systemd/system/ballot-front.service
$BDEBSTRAP_HOOKS/enable-units "$1" ballot-front

# cat ../services/eeprom-tool.service.tpl > $1/etc/systemd/system/eeprom-tool.service
# $BDEBSTRAP_HOOKS/enable-units "$1" eeprom-tool
